version: '2'
services:
  web:
    image: wordpress
    ports:
      - "80:80"
    volumes:
      - ./src/wordpress/wp-content:/var/www/html/wp-content
      - ./src/wordpress/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: db_pass
    links:
      - db:mysql
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
volumes:
  mysql-data:
    external: true